apiVersion: v1
kind: Service
metadata:
  name: spring-simple-api-service
spec:
  selector:
    app: springboot-cicd-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8100
  type: ClusterIP